### ISSUE TITLE
"Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details"

### ISSUE THREAD

**Issue by mido1978** [richibrics/IoTuring#127]
Hi, just tried to start IoTuring on Raspberry Pi in connection with HomeAssistant.
I installed all new with pipx command according to your documentation.
Setup the warehouse with HomeAssistant as also MQTT ends in the following error:

====================================================
`1 - Manage entities
2 - Manage warehouses
C - Start IoTuring
H - Help
Q - Quit

Select your choice: C

[ 2024-10-21 14:45:54 | Message  |         ConfiguratorIO        ]  Saved "/home/pi/.config/IoTuring/configurations.json"
[ 2024-10-21 14:45:54 |   Info   |              App              ]  Name: IoTuring
[ 2024-10-21 14:45:54 |   Info   |              App              ]  Version: 2023.11.1
[ 2024-10-21 14:45:54 |   Info   |              App              ]  Description: Simple and powerful cross-platform script to control your pc and share statistics
                                                                    using communication protocols like MQTT and home control hubs like HomeAssistant.
[ 2024-10-21 14:45:54 |   Info   |          Configurator         ]  Run the script with -c to enter configuration mode
[ 2024-10-21 14:45:54 |   Info   |         Entity.AppInfo        ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |       Entity.Temperature      ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |        Entity.Hostname        ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |          Entity.Power         ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |          Entity.Disk          ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |           Entity.Cpu          ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |   Info   |           Entity.Ram          ]  Initialization successfully completed
[ 2024-10-21 14:45:54 |  Error   |         Entity.Monitor        ]  Initialization interrupted due to an error:
[ 2024-10-21 14:45:54 |  Error   |         Entity.Monitor        ]  Xset not supported: xset command not found!
[ 2024-10-21 14:45:54 |   Info   |         EntityManager         ]  Entity.Monitor unloaded
[ 2024-10-21 14:45:54 |   Info   |              MQTT             ]  Preparing MQTT client
Traceback (most recent call last):
  File "/home/pi/.local/bin/IoTuring", line 8, in <module>
    sys.exit(loop())
  File "/home/pi/.local/pipx/venvs/IoTuring/lib/python3.7/site-packages/IoTuring/__init__.py", line 52, in loop
    warehouse.Start()
  File "/home/pi/.local/pipx/venvs/IoTuring/lib/python3.7/site-packages/IoTuring/ClassManager/../Warehouse/Deployments/MQTTWarehouse/MQTTWarehouse.py", line 37, in Start
    self.GetFromConfigurations(CONFIG_KEY_PASSWORD))
  File "/home/pi/.local/pipx/venvs/IoTuring/lib/python3.7/site-packages/IoTuring/Protocols/MQTTClient/MQTTClient.py", line 38, in __init__
    self.SetupClient()
  File "/home/pi/.local/pipx/venvs/IoTuring/lib/python3.7/site-packages/IoTuring/Protocols/MQTTClient/MQTTClient.py", line 45, in SetupClient
    self.client = MqttClient.Client(self.name)
  File "/home/pi/.local/pipx/venvs/IoTuring/lib/python3.7/site-packages/paho/mqtt/client.py", line 773, in __init__
    "Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details"
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details`
==========================================================

Some research brought me to this: [https://github.com/eclipse/paho.mqtt.python/blob/master/docs/migrations.rst](url). Is it connected? Maybe my Paho-MQTT Version  is too new?

Thanks in advance for a hint or help.

**Comment by infeeeee** [comment]
Please reply if the problem persist, it should be solved by updating IoTuring

**Comment by mido1978** [comment]
> Please reply if the problem persist, it should be solved by updating IoTuring

sorry, took a while to start investigation again.
But meanwhile I found out, that IOTuring could not be updated to the latest version, as my Python was out-of-date (Version 3.7.x), but has to be on >=3.8

I am updating Python now and Install IOTuring again.

**Comment by infeeeee** [comment]
Python 3.8 is already EOL, so support for it could be dropped in the near future, for reference here is the status of python versions: https://devguide.python.org/versions/

What distro are you using? I can see Debian 10 Buster is still on 3.7, but 11 is already in 3.9.

Use docker version if it's too complex to upgrade your system, most things should work the same.

**Comment by mido1978** [comment]
> Python 3.8 is already EOL, so support for it could be dropped in the near future, for reference here is the status of python versions: https://devguide.python.org/versions/
> 
> 
> 
> What distro are you using? I can see Debian 10 Buster is still on 3.7, but 11 is already in 3.9.
> 
> 
> 
> Use docker version if it's too complex to upgrade your system, most things should work the same.

Its a Raspian OS installed. apt update + upgrade is clean meanwhile. Started to take upgrade to 3.13
