### ISSUE TITLE
HA Call to Reboot failed

### ISSUE THREAD

**Issue by maxgiordan** [richibrics/IoTuring#131]
Everything perfect, really a great job!
But I can't use the reboot from Home Assistant: Power-reboot command: Call to Reboot failed: Interactive authentication required.
I inserted in 
/etc/sudoers.d/power 
the line
USER ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /sbin/shutdown
Instead of USER I inserted the username I used to connect to the raspberry in ssh.

What am I doing wrong? Thanks.

**Comment by infeeeee** [comment]
That doc is a bit outdated. Recent linux distros use polkit for managing those permissions, so you don't necessarily need sudo for that, you don't need to modify the sudoers  files, instead add a polkit rule. Create a file in `/etc/polkit-1/rules.d`, and add these for example for user `pi`:

```shell
$ sudo nano /etc/polkit-1/rules.d/49-power-nopasswd.rules
```

```js
polkit.addRule(function(action, subject) {
    if ((action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
        action.id == "org.freedesktop.login1.power-off-multiple-sessions" ) &&
        subject.user == "pi")
    {
        return polkit.Result.YES;
    }
});
```

More info about polkit in arch wiki, but these are true for all distros with systemd: https://wiki.archlinux.org/title/Polkit

---

Actually it's two things. [There is a mechanism in IoTuring](https://github.com/richibrics/IoTuring/blob/main/IoTuring/Entity/Deployments/Power/Power.py#L96) which tries to figure out what actual command you need for poweroff and reboot. It tries to call `poweroff --wtmp-only` without sudo. On most systems this fails, but raspbian already allows this with interactive authentication, so it doesn't fall back to using sudo, as NOPASSWD already added by default in `/etc/sudoers.d/010_pi-nopasswd`. 

What we could do in IoTuring is to allow to override the actual power commands by the user. If you would replace `reboot` with `sudo reboot` it would work with default config, without modifying the sudoers files.

I will think about how this workflow could be streamlined, and this example polkit rule should be added to the documentation.

---

After some more testing, I found this was a change in Raspbian 12 bookworm. I have an old rpi, still on Raspbian 11 bullseye, where everything is working as expected, without even modifying sudoers or polkit, with default config. `poweroff --wtmp-only` failes there, and correctly defaults to `sudo poweroff`

On the new rpi running 12, I needed the polkit rule. I guess you are on Raspbian 12 a well.

**Comment by maxgiordan** [comment]
Yes, bookworm 12 lite 64bit. Thank you so much for your work, really...

**Comment by infeeeee** [comment]
Did the polkit rule helped? Was that the problem or something else?

**Comment by maxgiordan** [comment]
I'm trying to figure out where I'm wrong: I did everything as I wrote above and replaced pi with my user...but when I press reboot button on HA it always gives same error "Interactive authentication required". I'm reading and rereading polkit info but I don't understand where I'm wrong...

**Comment by infeeeee** [comment]
what happens if you run `reboot`  manually in a terminal without sudo or anything? I assume you are in a session with the same user you want to run IoTuring as. If you can run `reboot` without a prompt and without sudo, than polkit is applied successfully, and the problem is with IoTuring. If you can't call reboot manually than you messed up something in the polkit rule.

**Comment by maxgiordan** [comment]
If I use another terminal authenticating with my user, rebooting without sudo produces the same error

**Comment by infeeeee** [comment]
Than the polkit rule is not working... Have you tried a standard  reboot? Some settings only applied if you logged out from all sessions, usually it's safer to just restart.

Also try to add the other two explicit actions as well, maybe you need them for some reason, it works for me without them:

```js
polkit.addRule(function(action, subject) {
    if (( action.id == "org.freedesktop.login1.reboot" ||
        action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
        action.id == "org.freedesktop.login1.power-off" ||
        action.id == "org.freedesktop.login1.power-off-multiple-sessions" ) &&
        subject.user == "pi")
    {
        return polkit.Result.YES;
    }
});
```

**Comment by maxgiordan** [comment]
Perfect. I'm bad, I got the indentation wrong...polkit is great. Now I have to make sure your IoTuring runs in the background and on every reboot...what do you think? Am I too cheeky?

**Comment by infeeeee** [comment]
It's documented here, very easy: https://github.com/richibrics/IoTuring/blob/main/docs/Autostart%20tips.md#linux

Did you needed the other 2 actions, or the multiple sessions were enough? Also it's javascript, indentation doesn't matter there.

**Comment by maxgiordan** [comment]
Thanks so much! Multiple sessions were enough.
You are great! Your IoTuring is really very well done...congratulations to the programmer and the person! @infeeeee
