### ISSUE TITLE
wrong unit for all cpu frequencies in homeassistant, should be mHz instead of Hz

### ISSUE THREAD

**Issue by Baxxy13** [richibrics/IoTuring#18]
All cpu_frequency sensors have the unit "Hz".
But modern pc's and sbc's working mostly in "MHz" range.
![ioturing_Test_3_Hz](https://user-images.githubusercontent.com/54898249/205997144-d61a1aa6-9ecb-4443-9c84-400a628fb465.JPG)

**Comment by richibrics** [comment]
Yes you're right, I checked it also on plutil documentation.
Fixed with [06c1203](https://github.com/richibrics/IoTuring/commit/06c1203d624d18b3771b04f2677165ce50bed48e)
