### ISSUE TITLE
macOS CPU Temperature

### ISSUE THREAD

**Issue by richibrics** [richibrics/IoTuring#23]
Hi @infeeeee 
I hope you can give me an advice on this question:
I found a simple macOS C++ program ([smctemp](https://github.com/narugit/smctemp)) that returns macOS cpu temperature.
The idea is to compile a x86 and an ARM version that will be included in the IoTuring package.

That project has a GPLv2 license, which prevents me from using that executable in my script.
Do I have any solution ?
What do you think if I downgrade IoTuring license to GPLv2 ?

Hope to hear good news,
Riccardo

**Comment by infeeeee** [comment]
- You can instruct users to install that program separately, than with `ctypes` you can call functions in python: https://docs.python.org/3/library/ctypes.html
- Call this executable in a subprocess

Searching about how this works there are a lot of other projects which can read temperatures some way on a mac. A lot of them are FOSS, so you can take a look what they are doing behind the scene, maybe some of them have some apis:

- https://github.com/hacker1024/coretemp - [bpytop](https://github.com/aristocratos/bpytop) reads temperature from here. I think this is the best way, they are using a subprocess: https://github.com/aristocratos/bpytop/blob/master/bpytop.py#L3227
- https://apple.stackexchange.com/questions/54329/can-i-get-the-cpu-temperature-and-fan-speed-from-the-command-line-in-os-x
- https://github.com/jkuri/macstats
- https://github.com/sadponyguerillaboy/SMC-Toolkit - This seems interesting, c++ plus python
- https://github.com/kethan1/MacTmp/ - it reads `powermetrics`, so root only
- https://github.com/lavoiesl/osx-cpu-temp - it works without sudo, bpytemp uses this as well
- https://github.com/DanielStormApps/Fanny
- https://github.com/Chris911/iStats

MIT license is compatible with GPL3, so you can reuse that code, with attribution. IANAL but just checking what apis are the calling is not copying, you just use them as a "documentation", which falls into fair use.

**Comment by richibrics** [comment]
You're always great with your explanations.

I followed your tip and gave up on smctemp.
I think I found a solution:
forked a repo that has smc functions (in c) wrapped for Python usage and removed unnecessary files.
I linked that new repo in optional dependencies for macOS, so it's downloaded and compiled while installing IoTuring only for macOS.
Used the library in the script (macOS side).

What do you think about this ?

**Comment by infeeeee** [comment]
Nice work, I found your fork!

If it works it's definitely a more elegant solution than a subprocess.

The problem is that now you have to maintain one more repo :)

**Comment by richibrics** [comment]
Nice, 
well I will work on that repo when I need macOS specific functions, never else
