### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by infeeeee** [richibrics/IoTuring#3]
Please choose a license for this nice project: https://choosealicense.com/

No license means all rights reserved, and noone can contribute legally: https://choosealicense.com/no-permission/

I recommend MIT for a project like this.

**Comment by richibrics** [comment]
Hi, you're right thanks. 
I added GNU GPLv3 license that should work for this project. Let me know if everything is okay.

RB

**Comment by infeeeee** [comment]
Nice, thanks!
