### ISSUE TITLE
implement CPU-Temperature (linux)

### ISSUE THREAD

**Issue by Baxxy13** [richibrics/IoTuring#4]
I found your nice Project und used it to push the system data of an proxmox-server into an Homeassistant.
Works without problems since on week.

The only sensor i miss is cpu-temperature.
Is it possible to implement such sensor?

**Comment by richibrics** [comment]
Hi, could you please run this short script in python and send me the output ? Thank you

```
import psutil

if __name__ == "__main__":
    print(psutil.sensors_temperatures())
```

You need psutil to run this, but you should already have it since you're currently using IoTuring

**Comment by Baxxy13** [comment]
Hi, sorry for late reply.
I'm not very familiar with python but i got output.

my Proxmox-Server (4 Core - Celeron J4125):
`{'acpitz': [shwtemp(label='', current=47.0, high=95.0, critical=95.0)], 'coretemp': [shwtemp(label='Package id 0', current=48.0, high=105.0, critical=105.0), shwtemp(label='Core 0', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 1', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 2', current=47.0, high=105.0, critical=105.0), shwtemp(label='Core 3', current=47.0, high=105.0, critical=105.0)]}`

and testet on RaspberryPi 3B+:
`{'cpu_thermal': [shwtemp(label='', current=44.546, high=None, critical=None)]}`

To keep it simple i think you can use the "shwtemp - current" rounded to 1 decimal place after the comma (e.g. 44.5 for the Pi).
I don't need the temperatures for every core.

Greetings, Baxxy

**Comment by richibrics** [comment]
Thank you so much.
I'd say to add a Temperature sensor for each dict entry, for example if your system had had both "acpitz" and "cpu_thermal" you would have seen two sensors: "acpitz temperature" and "cpu_thermal temperature".

Then for each sensor I see that there are a lot of temperatures. I'd say to consider them all and to send the maximum one, but let me know if the average would be more interesting in your opinion.

What do you think @infeeeee @Baxxy13 ?

Let me know.

**Comment by richibrics** [comment]
Otherwise also all temperatures may be sent as single entities. Let me know.

**Comment by infeeeee** [comment]
On a healthy system usually per core temperatures are not too different, so sending the first, average or maximum will be really close, so shouldn't matter too much. 

It would be nice to send all sensors of a device as extra attributes, they are accessible for automations in HA. I mean, for this MQTT light, I can see these in HA, we can add there other sensors:
![kép](https://user-images.githubusercontent.com/1271737/196528968-a3099bd5-540c-4685-a8a5-496b658a8e86.png)
(Sorry, my HA is in Hungarian)

A possible problem for this, if on my server psutil can't read the label of some sensors:
```
'it8792': [
    shwtemp(label='', current=29.0, high=127.0, critical=127.0), 
    shwtemp(label='', current=34.0, high=127.0, critical=127.0), 
    shwtemp(label='', current=34.0, high=127.0, critical=127.0)], 
```

On `sensors`  command they look like this:
```
it8792-isa-0a60
Adapter: ISA adapter
temp1:        +29.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp2:        +34.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
temp3:        +34.0°C  (low  = +127.0°C, high = +127.0°C)  sensor = thermistor
```
so expect 'label' can be empty

---

Also psutil can't report temperatures on windows, but it can be achieved with [wmi](https://pypi.org/project/WMI/) and [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) as answered here: https://stackoverflow.com/questions/3262603/accessing-cpu-temperature-in-python (LibreHardwareMonitor (LHM) is a maintained fork of OpenHardwareMonitor)

This works on my windows box, when LHM is running:

```python
import wmi
w = wmi.WMI(namespace="root\LibreHardwareMonitor")
temperature_infos = w.Sensor()
for sensor in temperature_infos:
    if sensor.SensorType==u'Temperature':
        print(sensor.Name)
        print(sensor.Value)
```

**Comment by Baxxy13** [comment]
> On a healthy system usually per core temperatures are not too different, so sending the first, average or maximum will be really close, so shouldn't matter too much.

I also think one temperature-sensor for the whole system should be enough.
I would prefer the highest, but average or the first one are also fine.

**Comment by richibrics** [comment]
Hi, could you try the TemperatureSensor branch latest commit (#12) ?
I've also added the extra attributes, so if you can send me a picture of the sensor with the extra attributes in HomeAssistant would be nice to check the status of the implementation.

Keep in mind that currently this works only under Linux, so don't try the update in macOS/Windows.

Thanks !

**Comment by richibrics** [comment]
Updated it again, don't test the previous commit but the current one please

**Comment by Baxxy13** [comment]
Hi,
i'm sorry to say, but i don't know how to install / test these "TemperatureSensor - Branch".
Can you give me some help?

**Comment by Baxxy13** [comment]
Thanks.
But unfortunately there's errors at the first command (git clone):
```
root@Herobox-PVE:~# git clone -b TemperatureSensor git@github.com:richibrics/IoTuring.git
Cloning into 'IoTuring'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Baxxy13** [comment]
Ok, i've managed to install and testing.

It looks good, is see 2 temperatures via the console warehouse...
```
[ 2022-12-06 18:40:50 | Message  |       Warehouse.Console       ]  Entity.Os.operating_system: Linux
[ 2022-12-06 18:40:50 | Message  |       Warehouse.Console       ]  Entity.Temperature.acpitz: 44.0
[ 2022-12-06 18:40:50 | Message  |       Warehouse.Console       ]  Entity.Temperature.coretemp: 43.0
```
... and via MQTT-Explorer connected to the HA-Mosquitto
![ioturing_Test](https://user-images.githubusercontent.com/54898249/205983950-22b213d2-17e4-4072-9787-6c369c4b3e36.JPG)

But the "Device" was not created in HA like the Device from an RaspberryPi with older IoTuring.

I check if i can find out if it's related to my HA.

**Comment by richibrics** [comment]
That's strange; have you added the HomeAssistant Warehouse in the configurations ?

**Comment by Baxxy13** [comment]
> That's strange; have you added the HomeAssistant Warehouse in the configurations ?

It was my fault. I used MQTT warehause instead of Homeassistant warehouse. 
After correcting this everything works fine now.

**Comment by richibrics** [comment]
Perfect, now I'll look at methods to get temperature on Windows and macOS.
Thank you for you support, I'm always here for every suggestion/problem.
