### ISSUE TITLE
Change folder for Logs like we did for configurations

### ISSUE THREAD

**Issue by richibrics** [richibrics/IoTuring#58]
I wouldn't place them in configurations folders, so I still need to find the correct place.

Logs are currently saved in script folder and this isn't a great way to store them.

**Comment by infeeeee** [comment]
Also logrotation should be handled. IoTuring just creates new logs at each restart, old ones should be deleted.

Python built in `logging` library has some functions for this: https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler

Maybe we should change to this library from this custom logger?
