### ISSUE TITLE
Cannot find configurations.json file on Windows 11 machine

### ISSUE THREAD

**Issue by kuro6** [richibrics/IoTuring#85]
I've set up IoTuring on Windows 11. Everything is running smoothly - I see the MQTT device in Home Assistant but I do not see the configurations.json file that's supposed to be found on my local machine in C:\Users\username\AppData\Roaming\IoTuring\. The IoTuring folder does not even exist in the Roaming folder. Any advice? Thanks.

IoTuring version is 2023.11.1.

Copy of command prompt output after setting up IoTuring:
`[ 2023-12-02 00:23:27 | Message  |         ConfiguratorIO        ]  Saved "C:\Users\username\AppData\Roaming\IoTuring\configurations.json"`

**Comment by richibrics** [comment]
Does IoTuring keep the configurations between one run of the configuration
mode and the other ? Or what you set (entities and warehouses) are lost as
soon as you exit from IoTuring ?

Il giorno sab 2 dic 2023 alle 07:51 kuro6 ***@***.***> ha
scritto:

**Comment by kuro6** [comment]
IoTuring keeps the configuration between runs.

**Comment by infeeeee** [comment]
@kuro6 Could you find your config file? In the new version there is an option to open configuration file in your default editor, it should help. Just run `IoTuring -o`

**Comment by richibrics** [comment]
I close this issue due to inactivity. The script has been updated since the issue had been open and now supports the `IoTuring -o` argument to open the configuration file in an external editor.
Please reopen the issue if you still encounter problems.
